// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgVcKDqeBLksP98GmKx0561QOY61vvslw',
    appId: '1:994851235346:web:143fb5e4e90bc2ced01acb',
    messagingSenderId: '994851235346',
    projectId: 'flash-chat-22643',
    authDomain: 'flash-chat-22643.firebaseapp.com',
    storageBucket: 'flash-chat-22643.appspot.com',
    measurementId: 'G-GN8BTELC3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZb0oSy0Epl1Lvkrm1HX6FHpRn89fPfzg',
    appId: '1:994851235346:android:ad6e027bf9badab5d01acb',
    messagingSenderId: '994851235346',
    projectId: 'flash-chat-22643',
    storageBucket: 'flash-chat-22643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOuxzdaBW0PTNjP9XnilD4Y31-ZvWlHYU',
    appId: '1:994851235346:ios:d3f64f10dad95fccd01acb',
    messagingSenderId: '994851235346',
    projectId: 'flash-chat-22643',
    storageBucket: 'flash-chat-22643.appspot.com',
    iosClientId: '994851235346-u2ih9g36j9vctllgpkus72f2mofid4d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOuxzdaBW0PTNjP9XnilD4Y31-ZvWlHYU',
    appId: '1:994851235346:ios:d3f64f10dad95fccd01acb',
    messagingSenderId: '994851235346',
    projectId: 'flash-chat-22643',
    storageBucket: 'flash-chat-22643.appspot.com',
    iosClientId: '994851235346-u2ih9g36j9vctllgpkus72f2mofid4d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );
}
